artifacts_root : artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/gbiamgaurav/branching_datasets/raw/main/En-Hi-text-transalation.zip
  local_data_file: artifacts/data_ingestion/text_data.zip
  unzip_dir: artifacts/data_ingestion